<?php

namespace Citas\Bundle\CitasBundle\Entity;

/**
 * ObservacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservacionesRepository extends \Doctrine\ORM\EntityRepository
{
}
