<?php

namespace Registro\Bundle\RegistroBundle\Entity;

/**
 * MascotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MascotaRepository extends \Doctrine\ORM\EntityRepository
{
}
