<?php

namespace Inventario\Bundle\InventarioBundle\Entity;

/**
 * InventarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventarioRepository extends \Doctrine\ORM\EntityRepository
{
}
