<?php

namespace Inventario\Bundle\InventarioBundle\Entity;

/**
 * MedicamentosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicamentosRepository extends \Doctrine\ORM\EntityRepository
{
}
