observaciones:
    path:     /
    defaults: { _controller: "CitasBundle:Observaciones:index" }

observaciones_show:
    path:     /{id}/show
    defaults: { _controller: "CitasBundle:Observaciones:show" }

observaciones_new:
    path:     /new
    defaults: { _controller: "CitasBundle:Observaciones:new" }

observaciones_create:
    path:     /create
    defaults: { _controller: "CitasBundle:Observaciones:create" }
    methods:  POST

observaciones_edit:
    path:     /{id}/edit
    defaults: { _controller: "CitasBundle:Observaciones:edit" }

observaciones_update:
    path:     /{id}/update
    defaults: { _controller: "CitasBundle:Observaciones:update" }
    methods:  [POST, PUT]

observaciones_delete:
    path:     /{id}/delete
    defaults: { _controller: "CitasBundle:Observaciones:delete" }
    methods:  [POST, DELETE]
